# Generated by Django 5.2.1 on 2025-05-18 22:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Capacity",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "schema",
                    models.JSONField(
                        default=dict,
                        help_text="JSON schema of hall layout",
                        verbose_name="Seating Schema",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this hall is available for scheduling",
                        verbose_name="Active",
                    ),
                ),
                (
                    "maintenance_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about hall maintenance or issues",
                        verbose_name="Maintenance Notes",
                    ),
                ),
                (
                    "floor",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Floor Number"
                    ),
                ),
                (
                    "accessibility_features",
                    models.JSONField(
                        default=list,
                        help_text="List of accessibility features available",
                        verbose_name="Accessibility Features",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hall",
                "verbose_name_plural": "Halls",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SeatCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "price_modifier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier for base ticket price",
                        max_digits=5,
                        verbose_name="Price Modifier",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        default="#FFFFFF",
                        help_text="HEX color code for UI representation",
                        max_length=7,
                        verbose_name="Color Code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seat Category",
                "verbose_name_plural": "Seat Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("row", models.PositiveSmallIntegerField(verbose_name="Row Number")),
                (
                    "number",
                    models.PositiveSmallIntegerField(verbose_name="Seat Number"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this seat is available for booking",
                        verbose_name="Active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional information about the seat",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "coordinates",
                    models.JSONField(
                        default=dict,
                        help_text="X,Y coordinates for interactive schema",
                        verbose_name="Coordinates",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="halls.hall",
                        verbose_name="Hall",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seats",
                        to="halls.seatcategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seat",
                "verbose_name_plural": "Seats",
                "ordering": ["hall", "row", "number"],
                "unique_together": {("hall", "row", "number")},
            },
        ),
    ]
