"""Initial migration for halls app."""

# Generated by Django 5.0.2 on 2025-05-16 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial migration class for halls app."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Name"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Capacity",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "schema",
                    models.JSONField(
                        default=dict, verbose_name="Seating Schema"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hall",
                "verbose_name_plural": "Halls",
                "ordering": ["name"],
            },
        ),
    ]
