# Generated by Django 5.0.2 on 2025-05-18 19:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import shows.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Actor",
                "verbose_name_plural": "Actors",
                "indexes": [
                    models.Index(
                        fields=["name"], name="shows_actor_name_77c99a_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
                "indexes": [
                    models.Index(
                        fields=["name"], name="shows_genre_name_d015c1_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modified"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "poster",
                    models.ImageField(
                        upload_to="posters/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            ),
                            shows.models.validate_image_size,
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "actors",
                    models.ManyToManyField(
                        related_name="shows", to="shows.actor"
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shows",
                        to="shows.genre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Show",
                "verbose_name_plural": "Shows",
            },
        ),
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(db_index=True)),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performances",
                        to="shows.show",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance",
                "verbose_name_plural": "Performances",
                "ordering": ["-date_time"],
            },
        ),
        migrations.AddIndex(
            model_name="show",
            index=models.Index(
                fields=["title"], name="shows_show_title_4dbf33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="show",
            index=models.Index(
                fields=["status"], name="shows_show_status_e643ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performance",
            index=models.Index(
                fields=["date_time"], name="shows_perfo_date_ti_abd7b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performance",
            index=models.Index(
                fields=["show", "date_time"],
                name="shows_perfo_show_id_ad255c_idx",
            ),
        ),
    ]
